apiVersion: v1
kind: ServiceAccount
metadata:
  name: websites-watcher-egressgw-service-account
  namespace: {{ namespace }}
  labels:
    app: websites-watcher-egressgw
    app.kubernetes.io/name: websites-watcher-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: websites-watcher
    istio.io/rev: 1-18-2